export const indexImages = [
  {src: '/img/schema.jpg', alt: ''},
  {src: '/img/notebook.jpg', alt: ''},
  {src: '/img/amd-cpu.jpg', alt: ''},
  {src: '/img/brain.jpg', alt: ''},
  {src: '/img/cooler.jpg', alt: ''},
  {src: '/img/disk.jpg', alt: ''},
  {src: '/img/gpu-rtx.jpg', alt: ''},
  {src: '/img/gpu-rtx-large.jpg', alt: ''},
  {src: '/img/intel-cpu.jpg', alt: ''},
  {src: '/img/intel-cpu-large.jpg', alt: ''},
  {src: '/img/keyboard.jpg', alt: ''},
  {src: '/img/monitors.jpg', alt: ''},
  {src: '/img/mouse.jpg', alt: ''},
  {src: '/img/msi-motherboard.jpg', alt: ''},
];